apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: canary
  name: canary
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: standard
  volumeMode: Filesystem